kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: agentanvil-dev

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc]
    runtime_type = "io.containerd.runsc.v1"

nodes:
- role: control-plane
  image: agentanvil/kind-node:gvisor-v1.35.0