//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTask) DeepCopyInto(out *AgentTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTask.
func (in *AgentTask) DeepCopy() *AgentTask {
	if in == nil {
		return nil
	}
	out := new(AgentTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskList) DeepCopyInto(out *AgentTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskList.
func (in *AgentTaskList) DeepCopy() *AgentTaskList {
	if in == nil {
		return nil
	}
	out := new(AgentTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskSpec) DeepCopyInto(out *AgentTaskSpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ModelSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolSpec, len(*in))
		copy(*out, *in)
	}
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(WorkspaceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckpointPolicy != nil {
		in, out := &in.CheckpointPolicy, &out.CheckpointPolicy
		*out = new(CheckpointPolicySpec)
		**out = **in
	}
	if in.Replay != nil {
		in, out := &in.Replay, &out.Replay
		*out = new(ReplaySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskSpec.
func (in *AgentTaskSpec) DeepCopy() *AgentTaskSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTaskStatus) DeepCopyInto(out *AgentTaskStatus) {
	*out = *in
	if in.Phase != "" {
		in, out := &in.Phase, &out.Phase
		*out = *in
	}
	if in.CurrentStep != 0 {
		in, out := &in.CurrentStep, &out.CurrentStep
		*out = *in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.TraceURL != "" {
		in, out := &in.TraceURL, &out.TraceURL
		*out = *in
	}
	if in.PodName != "" {
		in, out := &in.PodName, &out.PodName
		*out = *in
	}
	if in.Reason != "" {
		in, out := &in.Reason, &out.Reason
		*out = *in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTaskStatus.
func (in *AgentTaskStatus) DeepCopy() *AgentTaskStatus {
	if in == nil {
		return nil
	}
	out := new(AgentTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// Helper DeepCopy functions for other structs in AgentTaskSpec.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(APIKeySecretRef)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]any, len(*in))
		for key, val := range *in {
			var outVal any
			switch v := val.(type) {
			case string:
				outVal = v
			case int:
				outVal = v
			case float64:
				outVal = v
			default:
				outVal = v
			}
			(*out)[key] = outVal
		}
	}
}

func (in *WorkspaceSpec) DeepCopyInto(out *WorkspaceSpec) {
	*out = *in
	if in.InitCommand != nil {
		in, out := &in.InitCommand, &out.InitCommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
	in.EphemeralStorage.DeepCopyInto(&out.EphemeralStorage)
}

func (in *CheckpointPolicySpec) DeepCopyInto(out *CheckpointPolicySpec) {
	*out = *in
}

func (in *ReplaySpec) DeepCopyInto(out *ReplaySpec) {
	*out = *in
}
